# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 269bf8a95270691d05213bb0c2dcac5e519db23f5c7b42d87fb3f4e74abdfbae327e73e0f2741b7fc495ee33a0ff90ff34ab6d29abe545475957d70d53b1955d

test:
  secret_key_base: 01b99e74d7e625fb633992ef780e0020b1c045cad9cfd5bffeb668aa20f582b7f7eaff72cd192b6633c61a283551e0fa2a908315cdc3376a1ac55a0cc4d35481

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
